language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: wsumquBVzncIrzrKTgFJY+LbtsQsHT9WFom1IO/ES5+AQCTYEjBtIMf2y33ycW50amiOGra4ZTrQv3z8AGuTozYTFAL30HOv9Ssztyx9Pc+MhqPvbTxrw9le5GYWxHznHeIhJ26Ln/44DSJcTlbzQCJoFTevloZCUignbAHVJ1OssHUNO/JqBepSeHEJc8LT6gEyChU39DHGdhFLsdE6mhZ2/RduQ+zmurxBMF0N4M/1ceCBqmgn3kI/fpCnBk9bRq8iE7O/GZYfbzd1waUHgYrUxvyW/mjvmefwkAsnQD7UQpeNsCqQqjcPorpmDlQD7OO6OTGyqyRFgN0Kvef5Ef7ZRmmI3QlIz9rF90B1ziMxyqTCOfp1iV3Lj7SFfIH5+0gqSiHpcDGGNdYxKhibccR1O3moauRInEehsZGg+K97fIaGesGXV/8EO3JSyrotyMAqWzK9a2MMP3RzKz5RHXAiT1xmzfNBp4lOwjOQLhhKrIJCqglvG6OwmK3tN7UDQfmnZBNjet/EyvwWqi1OEFHqfVgYoU0xUVlK+BeIxY+VUA0T/n/G2tyviQpPEdn69MBsveXLXk07o6/8B4aEYbj8BCkV0fp6glKn/QEmQo33UnOmuOwLfUuTFgsxnyXvQYrSUzgQ3HqAgNmPkXYSDALrtmPjBXDYVv8T6wbtFyQ=
  app:
    master: ml-test-app
  on: master
notifications:
  slack:
    secure: J6S6fTbMezCZ0hTb5kuAbjjfwUAP2v6oKY/WtDFUbRx4hqgs0sloSPzuXWhHxoyauYBvMAAk7tjzxhmL3PBxlZur5EhshRtW0AJ9JYz1dXAY9gFRkOeyQpRpPHeVWazluqsu9NQSTDqpphLWYG9GNvxmX0dSfkRUV0m9439ifvqEtnNXtMsBPFUtvGcRifBMM828ba3wwblJIsu3c/IDfclI3FEd9r3+5968DNfJ2pkuj6X85alrudNdMw8QxvqurAEALf8N66tpfKes1CNn/USJlncvj3WINBFicy6ZvMCXcx0o6KBAErdbgurSy02W87KpckDpMK0MHpuJXV4dlVZVohqWGdG2qO0cnwwooR+v5apgEjyNbHnwP9RbOV2M/GvPISIZNuNBTL6z/Qkbm3XyLSMjPNu1pjJ9Eyc/IxWryXFwfYI9cC43WSmeQnT1GYbmIK+S2+ghR/vqj8/n+Et0NvoiM9bNsSpWn4jQxCack5i0Hzj+Kebozr6iHmdw/0+fcfBcoqhI7w4ob0gF9ZVk1QSJ5NzPt4EgDdX2hGFRY73r7Sb/ApCydGxLYfLmVLmjWTAimVwIgvcXY9LT+4aD1+u/y60QSQPhZsE+I7dszZNaZI4kCY3aK0RSlK7sKSAIlaIp9g9FRe/beiUpv3GU1V7ecdzVDV27RAo0kLw=
