language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: xyutvSda6+JF8Fq+InoZOiL4xaNrjqbfdCbR/dUcSkmX+BAiELEq2ISS6yJou165b9Sggg1CTy0P4iJbtIeq1DvriFT4JowRNEZU2VMv/556eCpF8N4F70JCWePRyGSv+NloJJt/A+gZYYJvbsewlgCjz2A93Ued952KltVlLq3pRehdLQS+ESMIt/1F/aut14cTP5yBH5cnjBuREmtW9qHJfce/HaDHpLOD54O7fyRjctQ9ndaMuJ4v+mc6caKp483x0CBfTjj2F9rWVenVaqZmmMwYx4S01IzcIM3w5+C3as1OwXCU6LNh+UR3xgY1cowJ/Bwg+8vA1WZfOPWTI6HeZImLfefCO2iJEjzV/eX7imCckIv+LiNb5PaSKY+Hj+nj90b9u9aYWbYqjbbqlHlgNjvNl8CepFgTwFESuOdWQKm8Qk4OnLd8sYDIgv6Gd1p32/++uMi3sxxBRVCc7MPf8nq+25sHsYGJRkjQGSJs2c7Tmz+G+aS0zxpq342OyfYIjZNaHYWce3muBd/8T0mG3OPlf3vKd6qeOuoo8ZiECg2INbr0f0x4Tf3x/BTLlY77XsW3tArfjtABax9Bld9hbxnNyR/15Uvpzfr0QlMIqDQz1MDKSsbKe8TD4Z6I0xMKd/vGrFTUDJgEsC/EnMVZeAplKUHNAlYPIsaVDoc=
  app:
    master: ml-test-app
  on: master
